#!/bin/bash

# Copyright (c) 2024-2025 The Flatcar Maintainers.
# Use of this source code is governed by the Apache 2.0 license.

# Script to publish Flatcar images to Azure Shared Galley Images
tracestate="$(shopt -po xtrace || true)"
set +o xtrace
_="
${AZURE_CLIENT_ID}
${AZURE_CLIENT_SECRET}
"
eval "${tracestate}"

# Set defaults for environment variables (allow override via --env or directly in script)
AZURE_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-d38033ba-ec21-470c-96cf-4c6db9658d8b}"
AZURE_TENANT_ID="${AZURE_TENANT_ID:-f41c056a-c993-42d0-8d91-57f0ff222694}"
IMAGE_PUBLISHER_NAME="${IMAGE_PUBLISHER_NAME:-flatcar}"
IMAGE_PUBLISHER_URI="${IMAGE_PUBLISHER_URI:-https://www.flatcar.org/}"
IMAGE_PUBLISHER_CONTACT="${IMAGE_PUBLISHER_CONTACT:-infra@flatcar-linux.org}"
IMAGE_EULA_URL="${IMAGE_EULA_URL:-https://www.flatcar.org/license}"
VHD_STORAGE_ACCOUNT_NAME="${VHD_STORAGE_ACCOUNT_NAME:-flatcar}"
AZURE_LOCATION="${AZURE_LOCATION:-westeurope}"
PUBLISHING_SIG_RESOURCE_GROUP="${PUBLISHING_SIG_RESOURCE_GROUP:-sayan-flatcar-image-gallery-publishing}"
STAGING_SIG_RESOURCE_GROUP="${STAGING_SIG_RESOURCE_GROUP:-sayan-flatcar-image-gallery-staging}"
FLATCAR_STAGING_GALLERY_NAME="${FLATCAR_STAGING_GALLERY_NAME:-sayan_flatcar_staging}"
FLATCAR_GALLERY_NAME="${FLATCAR_GALLERY_NAME:-sayan_flatcar}"
FLATCAR_VERSION="${FLATCAR_VERSION:-3374.2.1}"
FLATCAR_CHANNEL="${FLATCAR_CHANNEL:-stable}"
FLATCAR_ARCH="${FLATCAR_ARCH:-amd64}"
FLATCAR_IMAGE_NAME="flatcar-${FLATCAR_CHANNEL}-${FLATCAR_ARCH}"
FLATCAR_IMAGE_OFFER="${FLATCAR_IMAGE_OFFER:-${FLATCAR_CHANNEL}}"
FLATCAR_IMAGE_SKU="${FLATCAR_IMAGE_SKU:-${FLATCAR_IMAGE_NAME}}"
VHD_STORAGE_SUBSCRIPTION_ID="${VHD_STORAGE_SUBSCRIPTION_ID:-${AZURE_SUBSCRIPTION_ID}}"
VHD_STORAGE_RESOURCE_GROUP_NAME="${VHD_STORAGE_RESOURCE_GROUP_NAME:-flatcar}"
VHD_STORAGE_CONTAINER_NAME="${VHD_STORAGE_CONTAINER_NAME:-publish}"
FLATCAR_COMMUNITY_GALLERY_PUBLIC_NAME_PREFIX="${FLATCAR_COMMUNITY_GALLERY_PUBLIC_NAME_PREFIX:-flatcar}"
BLACKLISTED_TARGET_REGIONS="${BLACKLISTED_TARGET_REGIONS:-polandcentral australiacentral2 brazilsoutheast centraluseuap eastus2euap eastusstg francesouth germanynorth jioindiacentral norwaywest southafricawest switzerlandwest uaecentral brazilus southcentralusstg}"

# Get list of non-blacklisted target regions
DEFAULT_TARGET_REGIONS=$(az account list-locations -o json | jq -r '.[] | select( .metadata.regionType != "Logical" ) | .name' | sort | grep -v -E "(${BLACKLISTED_TARGET_REGIONS// /|})" | tr '\n' ' ')
TARGET_REGIONS="${TARGET_REGIONS:-${DEFAULT_TARGET_REGIONS}}"

function publish-flatcar-image() {
  ensure-flatcar-staging-sig-image-version-from-vhd

  IMAGE_NAME="${FLATCAR_IMAGE_NAME}"
  IMAGE_VERSION="${FLATCAR_VERSION}"
  GALLERY_NAME="${FLATCAR_GALLERY_NAME}"
  RESOURCE_GROUP_NAME="${PUBLISHING_SIG_RESOURCE_GROUP}"

  if sig-image-version-exists; then
    return
  fi

  ensure-resource-group
  PUBLIC_NAME_PREFIX="${FLATCAR_COMMUNITY_GALLERY_PUBLIC_NAME_PREFIX}" ensure-community-sig
  IMAGE_OFFER="${FLATCAR_IMAGE_OFFER}" IMAGE_PUBLISHER="${IMAGE_PUBLISHER_NAME}" ensure-image-definition

  SOURCE_VERSION="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${STAGING_SIG_RESOURCE_GROUP}"
  SOURCE_VERSION="${SOURCE_VERSION}/providers/Microsoft.Compute/galleries/${FLATCAR_STAGING_GALLERY_NAME}/images/${IMAGE_NAME}/versions/${IMAGE_VERSION}"

  copy-sig-image-version
}

function ensure-flatcar-staging-sig-image-version-from-vhd() {
  login

  IMAGE_NAME="${FLATCAR_IMAGE_NAME}"
  IMAGE_VERSION="${FLATCAR_VERSION}"
  GALLERY_NAME="${FLATCAR_STAGING_GALLERY_NAME}"
  RESOURCE_GROUP_NAME="${STAGING_SIG_RESOURCE_GROUP}"

  if sig-image-version-exists; then
    return
  fi

  ensure-resource-group
  ensure-sig
  IMAGE_OFFER="${FLATCAR_IMAGE_OFFER}" IMAGE_PUBLISHER="${IMAGE_PUBLISHER_NAME}" ensure-image-definition

  STORAGE_ACCOUNT_ID="/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${VHD_STORAGE_RESOURCE_GROUP_NAME}/providers/Microsoft.Storage/storageAccounts/${VHD_STORAGE_ACCOUNT_NAME}"
  VHD_URI="https://${VHD_STORAGE_ACCOUNT_NAME}.blob.core.windows.net/${VHD_STORAGE_CONTAINER_NAME}/flatcar-linux-${IMAGE_VERSION}-${FLATCAR_CHANNEL}-${FLATCAR_ARCH}.vhd"

  az sig image-version create \
    --resource-group "${RESOURCE_GROUP_NAME}" \
    --gallery-name "${GALLERY_NAME}" \
    --gallery-image-definition "${IMAGE_NAME}" \
    --gallery-image-version "${IMAGE_VERSION}" \
    --os-vhd-storage-account "${STORAGE_ACCOUNT_ID}" \
    --os-vhd-uri "${VHD_URI}"
}

function copy-sig-image-version() {
  az sig image-version create \
    --gallery-image-definition "${IMAGE_NAME}" \
    --gallery-image-version "${IMAGE_VERSION}" \
    --gallery-name "${GALLERY_NAME}" \
    --resource-group "${RESOURCE_GROUP_NAME}" \
    --exclude-from-latest "${EXCLUDE_FROM_LATEST:-false}" \
    --image-version "${SOURCE_VERSION}" \
    --target-regions ${TARGET_REGIONS}
}

function sig-image-version-exists() {
  if ! az sig image-version show \
    --gallery-image-definition "${IMAGE_NAME}" \
    --gallery-image-version "${IMAGE_VERSION}" \
    --gallery-name "${GALLERY_NAME}" \
    --resource-group "${RESOURCE_GROUP_NAME}" \
    --output none \
    --only-show-errors; then
    echo "SIG image ${RESOURCE_GROUP_NAME}/${GALLERY_NAME}/${IMAGE_VERSION}/${IMAGE_NAME} does not exist"
    return 1
  fi

  echo "SIG image ${RESOURCE_GROUP_NAME}/${GALLERY_NAME}/${IMAGE_VERSION}/${IMAGE_NAME} already exists"
  return 0
}

function ensure-image-definition() {
  local architecture
  case "${FLATCAR_ARCH}" in
    amd64) architecture=x64 ;;
    arm64) architecture=Arm64 ;;
    *) echo "Unsupported architecture: '${FLATCAR_ARCH}'"; exit 1 ;;
  esac

  az sig image-definition create \
    --gallery-image-definition "${IMAGE_NAME}" \
    --gallery-name "${GALLERY_NAME}" \
    --offer "${IMAGE_OFFER}" \
    --os-type Linux \
    --publisher "${IMAGE_PUBLISHER}" \
    --resource-group "${RESOURCE_GROUP_NAME}" \
    --sku "${IMAGE_NAME}" \
    --architecture "${architecture}" \
    --hyper-v-generation V2
}

function ensure-sig() {
  az sig create \
    --gallery-name "${GALLERY_NAME}" \
    --resource-group "${RESOURCE_GROUP_NAME}"
}

function ensure-community-sig() {
  az sig create \
    --gallery-name "${GALLERY_NAME}" \
    --resource-group "${RESOURCE_GROUP_NAME}" \
    --eula "${IMAGE_EULA_URL}" \
    --location "${AZURE_LOCATION}" \
    --public-name-prefix "${PUBLIC_NAME_PREFIX}"
}

function ensure-resource-group() {
  if ! az group show -n "${RESOURCE_GROUP_NAME}" -o none 2>/dev/null; then
    az group create -n "${RESOURCE_GROUP_NAME}" -l "${AZURE_LOCATION}"
  fi
}

function login() {
  AZURE_LOGIN_ERR_FILE=$(mktemp)
  echo "Authenticating to Azure using service principal."
  echo ${AZURE_CLIENT_ID}
  echo ${AZURE_TENANT_ID}
  tracestate="$(shopt -po xtrace || true)"
  set +o xtrace
  az login --service-principal \
  -u "${AZURE_CLIENT_ID}" \
  --identity >/dev/null 2>"$AZURE_LOGIN_ERR_FILE"
  if [[ $? -ne 0 ]]; then
    echo "Azure login failed. Error:"
    cat "$AZURE_LOGIN_ERR_FILE"
    rm -f "$AZURE_LOGIN_ERR_FILE"
    eval "${tracestate}"
    exit 1
  fi
  echo "Azure login successful."
  echo "Setting active subscription to ${AZURE_SUBSCRIPTION_ID}..."
  if ! az account set -s "${AZURE_SUBSCRIPTION_ID}" >/dev/null 2>&1; then
    echo "Failed to set Azure subscription."
    eval "${tracestate}"
    exit 1
  fi
  echo "Subscription set."

  eval "${tracestate}"
}

# Entrypoint
ensure-flatcar-staging-sig-image-version-from-vhd
