#!/bin/bash

# Prints packages which are in both gentoo-subset and flatcar-overlay

SCRIPT_ROOT=$(dirname $(readlink -f "$0"))
. "${SCRIPT_ROOT}/common.sh" || exit 1

DEFINE_string overlay_path "${SCRIPT_ROOT}/repos/flatcar-overlay" \
    "Directory containing the overlay"
DEFINE_string gentoo_subset_path "${SCRIPT_ROOT}/repos/gentoo-subset" \
    "Path to gentoo-subset"

# Parse flags
FLAGS "$@" || exit 1
eval set -- "${FLAGS_ARGV}"

function get_tree_packages() {
	# gets a list of all packages in a tree
	find "$1" -maxdepth 3 -type f -name "*.ebuild" -printf "%P\n" | xargs dirname | sort | uniq
}

gentoo_subset_packages=$(get_tree_packages ${FLAGS_gentoo_subset_path})
overlay_packages=$(get_tree_packages ${FLAGS_overlay_path})

all_packages="$gentoo_subset_packages $overlay_packages"
dups=$(sort <<< "$all_packages" | uniq -D | uniq)

if [[ -z "$dups" ]]; then
	info "No duplicate packages, all good!"
	exit 0
fi

warn "Found duplicate package(s):"
warn "$dups"
exit 1
