#cloud-config

coreos:
    units:
      - name: exoscale-ssh-key.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Sets SSH key from metadata

          [Service]
          Type=oneshot
          StandardOutput=journal+console
          ExecStart=/oem/bin/exoscale-ssh-key
      - name: exoscale-cloudinit.service
        command: restart
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from exoscale (cloudstack-style) metadata
          Requires=flatcar-setup-environment.service
          After=flatcar-setup-environment.service

          [Service]
          Type=oneshot
          EnvironmentFile=/etc/environment
          ExecStart=/oem/bin/exoscale-coreos-cloudinit
    oem:
      id: exoscale
      name: exoscale
      version-id: @@OEM_VERSION_ID@@
      home-url: http://www.exoscale.ch
      bug-report-url: https://github.com/coreos/coreos-overlay
