# Dracut configuration for FIPS mode
# Include SymCrypt OpenSSL provider + config for FIPS mode
install_items+=" /usr/lib64/ossl-modules/symcryptprovider.so "
install_items+=" /usr/lib64/libsymcrypt.so /usr/lib64/libsymcrypt.so.* "
install_items+=" /etc/pki/tls/openssl.cnf /etc/pki/tls/symcrypt_prov.cnf "
