ARG VERSION
FROM flatcar-sdk-import:${VERSION}

ARG BINHOST
ARG COREOS_OFFICIAL=0

RUN /home/sdk/sdk_entry.sh ./setup_board --board="arm64-usr" --binhost="${BINHOST}/arm64-usr"
RUN /home/sdk/sdk_entry.sh ./setup_board --board="arm64-usr" --regen_configs

RUN /home/sdk/sdk_entry.sh ./setup_board --board="amd64-usr" --binhost="${BINHOST}/amd64-usr"
RUN /home/sdk/sdk_entry.sh ./setup_board --board="amd64-usr" --regen_configs

RUN rm -rf /home/sdk/toolchain-pkgs
