#!/bin/bash

set -euo pipefail

SCRIPT_NAME="$(basename "$(realpath "${BASH_SOURCE[0]}")")"
SYSEXT_NAME="$(echo "$SCRIPT_NAME" | sed -e "s/^sysext_mangle_//" -e "s/\.sh$//")"
DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
. "$DIR/sysext_mangle_kmod"

rootfs="${1}"

pushd "${rootfs}"
configure_modprobe "$SYSEXT_NAME"
popd
