#!/bin/bash

set -euo pipefail
rootfs="${1}"

#find "${rootfs}"
# Remove debug
rm -rf "${rootfs}"/usr/{lib/debug/,lib64/cmake/,include/}

mkdir -p "${rootfs}"/usr/share/flatcar/etc
rm -rf "${rootfs}"/etc/{csh.env,environment.d/,profile.env}
cp -a "${rootfs}"/etc/. "${rootfs}"/usr/share/flatcar/etc/

#script_root="$(cd "$(dirname "$0")/../"; pwd)"
#files_dir="${script_root}/sdk_container/src/third_party/coreos-overlay/coreos/sysext/docker"

#echo ">>> NOTICE $0: installing extra files from '${files_dir}'"
#cp -va "${files_dir}/"* "${rootfs}"

#mkdir -p "${rootfs}/usr/lib/systemd/system/sockets.target.d"
#{ echo "[Unit]"; echo "Upholds=docker.socket"; } > "${rootfs}/usr/lib/systemd/system/sockets.target.d/10-docker-socket.conf"
