name: Get the latest mantle release for branch
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 1'

jobs:
  get-mantle-release:
    strategy:
      matrix:
        channel: [main,alpha,beta,stable,lts,lts-old]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out scripts at ${{ github.ref }} for GHA scripts only
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_PR_TOKEN }}
          path: gha
      - name: Figure out branch
        id: figure-out-branch
        run: gha/.github/workflows/figure-out-branch.sh '${{ matrix.channel }}'
      - name: Check out work scripts branch for updating
        if: steps.figure-out-branch.outputs.SKIP == 0
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_PR_TOKEN }}
          path: work
          ref: ${{ steps.figure-out-branch.outputs.BRANCH }}
      - name: Fetch latest mantle hash
        if: steps.figure-out-branch.outputs.SKIP == 0
        id: fetch-latest-mantle
        run: |
          set -euo pipefail
          commit=$(git ls-remote  https://github.com/flatcar/mantle refs/heads/main | cut -f1)
          echo "COMMIT=${commit}" >>"${GITHUB_OUTPUT}"
      - name: Try to apply patch
        if: steps.figure-out-branch.outputs.SKIP == 0
        env:
          WORK_SCRIPTS_DIR: "${{ github.workspace }}/work"
        run: |
          set -euo pipefail
          source gha/.github/workflows/common.sh
          set -x
          cd "${WORK_SCRIPTS_DIR}"
          commit=${{ steps.fetch-latest-mantle.outputs.COMMIT }}
          file=sdk_container/.repo/manifests/mantle-container
          echo "ghcr.io/flatcar/mantle:git-${commit}" > "${file}"
          git status --porcelain "${file}" | grep -q "^ M" || exit 0
          prepare_git_repo
          git commit --signoff -m "Update mantle container image to latest HEAD" "${file}"
          push_changes_with_rebase
