name: Sync GHCR Calico images with Docker Hub
on:
  schedule:
    # run every 12h
    - cron:  '0 */12 * * *'
  workflow_dispatch:

jobs:
  mirror-calico:
    runs-on: ubuntu-latest
    steps:
      - name: Check out scripts
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry (ghcr)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Figure out latest Calico release version
        id: calico-latest-release
        run: |
          set -exuo pipefail

          calico_version=$(curl \
                             -H 'Accept: application/vnd.github+json' \
                             'https://api.github.com/repos/projectcalico/calico/releases' | \
                           jq --raw-output '.[].tag_name' | \
                           sort --version-sort --reverse | \
                           head --lines=1)

          echo "Found version: ${calico_version}"
          echo "CALICO_VERSION=${calico_verison}" >>"${GITHUB_OUTPUT}"
      - name: Mirror calico images to GHCR
        env:
          CALICO_VERSION: ${{ steps.calico-latest-release.outputs.CALICO_VERSION }}
        run: |
          pushd .github/workflows/
          ./mirror-calico.sh "${CALICO_VERSION}"
          popd
