name: Keep Gentoo submodule updated
on:
  schedule:
    - cron: '0 4 * * 0-4'
  workflow_dispatch:

jobs:
  keep-gentoo-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Check out scripts
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.BOT_PR_TOKEN }}
          path: scripts
          sparse-checkout: |
            .gitmodules
            .github/workflows/common.sh
          sparse-checkout-cone-mode: false
      - name: Update Gentoo submodule
        id: update-gentoo
        env:
          WORK_SCRIPTS_DIR: "${{ github.workspace }}/scripts"
        run: |
          set -euo pipefail
          source scripts/.github/workflows/common.sh
          prepare_git_repo
          submodule=sdk_container/src/third_party/gentoo
          url=$(git -C "${WORK_SCRIPTS_DIR}" config --file .gitmodules --get "submodule.${submodule}.url")
          branch=$(git -C "${WORK_SCRIPTS_DIR}" config --file .gitmodules --get "submodule.${submodule}.branch")
          read -r latest_commit _ < <(git ls-remote --exit-code "${url}" "refs/heads/${branch}")
          short_commit=${latest_commit:0:12}
          git -C "${WORK_SCRIPTS_DIR}" update-index --cacheinfo "160000,${latest_commit},${submodule}"
          if git -C "${WORK_SCRIPTS_DIR}" diff --cached --quiet -- "${submodule}"; then
              echo 'UPDATE_NEEDED=0' >>"${GITHUB_OUTPUT}"
              exit 0
          fi
          git -C "${WORK_SCRIPTS_DIR}" commit --signoff -m "gentoo: Update to ${short_commit}"
          cleanup_repo
          echo 'UPDATE_NEEDED=1' >>"${GITHUB_OUTPUT}"
          echo "LATEST_COMMIT=${latest_commit}" >>"${GITHUB_OUTPUT}"
          echo "SHORT_COMMIT=${short_commit}" >>"${GITHUB_OUTPUT}"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        if: steps.update-gentoo.outputs.UPDATE_NEEDED == 1
        with:
          token: ${{ secrets.BOT_PR_TOKEN }}
          path: scripts
          branch: buildbot/update-gentoo-submodule
          delete-branch: true
          title: Update gentoo submodule to ${{ steps.update-gentoo.outputs.SHORT_COMMIT }}
          body: Update `sdk_container/src/third_party/gentoo` to flatcar-hub/gentoo@${{ steps.update-gentoo.outputs.LATEST_COMMIT }}.
          labels: auto-ci,auto-jenkins,main
